# Generated by Django 6.0 on 2025-12-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=255, null=True)),
                ('printer', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('edition_size', models.CharField(blank=True, max_length=50, null=True)),
                ('dimensions_text', models.CharField(blank=True, max_length=255, null=True)),
                ('sheet_size', models.CharField(blank=True, max_length=255, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='secondstateapp.artwork')),
            ],
        ),
    ]
