# Generated by Django 6.0 on 2025-12-30 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_location', models.CharField(blank=True, max_length=255, null=True)),
                ('net_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auction_house', models.CharField(blank=True, max_length=255, null=True)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='secondstateapp.artwork')),
            ],
        ),
    ]
