# Generated by Django 6.0 on 2025-12-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0002_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
