# Generated by Django 6.0 on 2025-12-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0003_delete_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sale_location', models.CharField(blank=True, max_length=255, null=True)),
                ('net_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auction_house', models.CharField(blank=True, max_length=255, null=True)),
                ('purchased_location', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
