# Generated by Django 6.0 on 2025-12-31 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0004_soldpiece'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldPieceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sold_pieces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='secondstateapp.soldpiece')),
            ],
        ),
    ]
