# Generated by Django 6.0 on 2026-01-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0005_soldpieceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldpiece',
            name='link_to_sale',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soldpiece',
            name='sold_hammer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
