# Generated by Django 6.0 on 2026-01-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0006_soldpiece_link_to_sale_soldpiece_sold_hammer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldpiece',
            name='auction_house',
        ),
        migrations.RemoveField(
            model_name='soldpiece',
            name='net_sale_price',
        ),
        migrations.RemoveField(
            model_name='soldpiece',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='soldpiece',
            name='purchased_location',
        ),
    ]
