# Generated by Django 6.0 on 2026-01-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0007_remove_soldpiece_auction_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldpiece',
            name='link_to_sale',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
