# Generated by Django 6.0 on 2026-04-11 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0008_alter_soldpiece_link_to_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SoldPieceImage',
        ),
    ]
