# Generated by Django 6.0.6 on 2026-07-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0013_delete_auctionsearchjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True)),
                ('days_before', models.PositiveSmallIntegerField()),
                ('recipient_hash', models.CharField(max_length=64)),
                ('recipient_display', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('twilio_message_sid', models.CharField(blank=True, max_length=64)),
                ('twilio_status', models.CharField(blank=True, max_length=32)),
                ('covered_sale_hashes', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-target_date', 'days_before', 'recipient_display'],
                'constraints': [models.UniqueConstraint(fields=('target_date', 'days_before', 'recipient_hash'), name='unique_auction_reminder_digest')],
            },
        ),
        migrations.CreateModel(
            name='AuctionWatchLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('source_lot_id', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('artist_watchlist_name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('medium', models.CharField(blank=True, max_length=500)),
                ('auction_house', models.CharField(blank=True, max_length=255)),
                ('sale_title', models.CharField(blank=True, max_length=500)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('event_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('estimate_low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimate_high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lot_url', models.URLField(blank=True, max_length=2000)),
                ('sale_url', models.URLField(blank=True, max_length=2000)),
                ('source_status', models.CharField(blank=True, default='unchanged', max_length=24)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('source_first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_at', 'auction_house', 'artist', 'id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_lot_id'), name='unique_auction_watch_source_lot')],
            },
        ),
        # SoldPieceImage was removed from runtime code before this feature was
        # added. Align Django's migration state without deleting its legacy
        # database table or any historical images.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[migrations.DeleteModel(name='SoldPieceImage')],
        ),
    ]
