# Generated by Django 6.0.6 on 2026-07-20 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_reminder_control(apps, schema_editor):
    control = apps.get_model("secondstateapp", "AuctionReminderControl")
    control.objects.get_or_create(singleton_key=1, defaults={"active": False})


def delete_reminder_control(apps, schema_editor):
    control = apps.get_model("secondstateapp", "AuctionReminderControl")
    control.objects.filter(singleton_key=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0014_auctionreminderdelivery_auctionwatchlot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionReminderControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_source', models.CharField(blank=True, max_length=24)),
                ('last_run_status', models.CharField(blank=True, max_length=24)),
                ('last_run_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'auction reminder control',
                'verbose_name_plural': 'auction reminder control',
            },
        ),
        migrations.RunPython(create_reminder_control, delete_reminder_control),
    ]
