# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondstateapp", "0015_auction_reminder_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionwatchlot",
            name="artprice_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
