# Generated by Django 6.0.6 on 2026-07-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondstateapp", "0016_auctionwatchlot_artprice_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionMaxBidAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("currency", models.CharField(default="USD", max_length=8)),
                (
                    "resale_method",
                    models.CharField(
                        choices=[
                            ("median", "Median"),
                            ("mean", "Mean"),
                            ("recent", "Recent records"),
                            ("max", "Maximum"),
                            ("min", "Minimum"),
                            ("manual", "Manual"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "manual_resale_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("recent_count", models.PositiveIntegerField(default=3)),
                (
                    "expected_resale_hammer",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "net_resale_proceeds",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "inbound_shipping",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "target_profit",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "seller_commission_pct",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "outbound_shipping",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "other_resale_costs",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("premium_min", models.PositiveSmallIntegerField()),
                ("premium_max", models.PositiveSmallIntegerField()),
                ("sold_records_count", models.PositiveIntegerField()),
                ("comparables", models.JSONField(blank=True, default=list)),
                ("bid_rows", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="max_bid_analysis",
                        to="secondstateapp.auctionwatchlot",
                    ),
                ),
            ],
            options={
                "verbose_name": "auction max-bid analysis",
                "verbose_name_plural": "auction max-bid analyses",
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
