# Generated by Django 6.0.6 on 2026-08-05 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondstateapp', '0017_auctionmaxbidanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionEmailBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('recipient_keys', models.JSONField(blank=True, default=list)),
                ('recipient_snapshot', models.JSONField(blank=True, default=list)),
                ('subject_snapshot', models.TextField(blank=True)),
                ('html_body_snapshot', models.TextField(blank=True)),
                ('text_body_snapshot', models.TextField(blank=True)),
                ('gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuctionEmailBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('lot_snapshot', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='secondstateapp.auctionemailbatch')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_batch_items', to='secondstateapp.auctionwatchlot')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['selected_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='auctionemailbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_auction_email_batch'),
        ),
        migrations.AddConstraint(
            model_name='auctionemailbatch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('status__in', ('draft', 'sending', 'failed'))), models.Q(('is_active', False), ('status', 'sent')), _connector='OR'), name='auction_email_batch_active_status'),
        ),
        migrations.AddConstraint(
            model_name='auctionemailbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'lot'), name='unique_auction_email_batch_lot'),
        ),
    ]
