# Generated by Django 6.0.6 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secondstateapp", "0018_auctionemailbatch_auctionemailbatchitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionwatchlot",
            name="bid_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
